### ISSUE TITLE
Ubuntu: path for utills missing

### ISSUE THREAD

**Issue by gudzenkov** [ndbroadbent/dotfiles#8]
Linux  3.19.0-25-generic #26~14.04.1-Ubuntu x86_64
quickfix to use linuxbrew instead of brew, and for some reason $DOTFILES_PATH didn't get exported correctly

===== Executing the following scripts:
      [ git_config packages dropbox skype bashrc scm_breeze gnome conky startup apt-install rvm rvm_hooks ]

== Setting up git config...
setup/packages.sh: line 2: brew: command not found
....
setup/packages.sh: line 40: brew: command not found
== Installing dropbox nautilus extension...
== Installing skype...
==== Configuring skype to run on startup...
setup/skype.sh: line 22: /skype/configure_skype.sh: No such file or directory
== Run 'source ~/.bashrc' or 'source ~/.zshrc' to load SCM Breeze into your current shell.
./dev_machine_setup.sh: line 75: setup/gnome.sh: No such file or directory

**Comment by ndbroadbent** [comment]
Hi @gudzenkov, I hope you are doing well! I just realized I had one open issue on my dotfiles repo, and I'm sorry I never got back to you! I've switched from Linux to Mac now, but I hope you were able to figure this out!
